// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1eiCkMNFoW3HMnMI-F7gHZixkTdkO-0',
    appId: '1:891578854863:web:8112c0463a81a12deab6ba',
    messagingSenderId: '891578854863',
    projectId: 'vichtohuygo-expense-tracker',
    authDomain: 'vichtohuygo-expense-tracker.firebaseapp.com',
    storageBucket: 'vichtohuygo-expense-tracker.firebasestorage.app',
    measurementId: 'G-6VYKQYZGT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQjNeuRVsZ01pc_iIhRAoYPsI4M1SCDyg',
    appId: '1:891578854863:android:ccd2bfeda152061eeab6ba',
    messagingSenderId: '891578854863',
    projectId: 'vichtohuygo-expense-tracker',
    storageBucket: 'vichtohuygo-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWroNbfGC7uWCHfUFs3JQeaFeW1jtZYiA',
    appId: '1:891578854863:ios:221e880db24138bceab6ba',
    messagingSenderId: '891578854863',
    projectId: 'vichtohuygo-expense-tracker',
    storageBucket: 'vichtohuygo-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWroNbfGC7uWCHfUFs3JQeaFeW1jtZYiA',
    appId: '1:891578854863:ios:221e880db24138bceab6ba',
    messagingSenderId: '891578854863',
    projectId: 'vichtohuygo-expense-tracker',
    storageBucket: 'vichtohuygo-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1eiCkMNFoW3HMnMI-F7gHZixkTdkO-0',
    appId: '1:891578854863:web:1c2e6def21682abfeab6ba',
    messagingSenderId: '891578854863',
    projectId: 'vichtohuygo-expense-tracker',
    authDomain: 'vichtohuygo-expense-tracker.firebaseapp.com',
    storageBucket: 'vichtohuygo-expense-tracker.firebasestorage.app',
    measurementId: 'G-1155SWRMC0',
  );
}
